### ISSUE TITLE
Pop up not woring

### ISSUE THREAD

**Issue by ramarajpandiyan07** [ArtPavluk/mod_art_products#1]
i install your product in jd boston template .. when i click order button in product display. the page stuck and not showing pop up.. please resolve this

**Comment by pavluk** [comment]
Hello, tell me the site, by default the module works on bootstrap 2 (template protostar).
If you have another css Framework or not a standard template, you need to redefine the module and write a tweak to your template.
P.S If you need help in adapting the module for your template or revision, for a fee I can modify the module for you.
**[A new module release was released, layouts for various Frameworks](https://github.com/ArtPavluk/mod_art_products/releases/latest)**
